// lib/search/mappings-seed.js
// Curated search mappings — the cultural lexicon that turns human phrases into
// tags and related terms. Seeded into the search_mappings table (idempotent
// upsert via scripts/seed-mappings.mjs) and used as the in-code fallback when
// the database is unreachable, so search always understands these.
//
// mappedTags speak the brain's aesthetic vocabulary (matched case-insensitively
// against items.tags and the product_tags layer); relatedTerms are matched
// against product titles/brands as text. Admin can add more via /api/admin.
//
// asterisk-boost r1: 16 → 55 phrases. Every phrase is a real way people ask
// for clothes; every mapping is editorial judgement in the canonical axes.

export const DEFAULT_MAPPINGS = [
  { searchPhrase: "2012 chief keef", referenceType: "influencer", confidence: 0.8,
    mappedTags: ["streetwear", "statement"],
    relatedTerms: ["true religion", "ralph lauren", "polo", "designer sneaker", "varsity", "chicago drill", "early 2010s"] },
  { searchPhrase: "good blanks", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["minimal"],
    relatedTerms: ["premium basics", "blank tee", "heavyweight tee", "hoodie", "helmut lang", "yeezy", "yeezy gap"] },
  { searchPhrase: "boxy", referenceType: "fit", confidence: 0.9,
    mappedTags: ["minimal", "streetwear"],
    relatedTerms: ["boxy fit", "boxy hoodie", "boxy tee", "cropped fit", "oversized"] },
  { searchPhrase: "grungy", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["archival", "independent"],
    relatedTerms: ["dark", "distressed", "faded", "worn", "damaged", "grunge"] },
  { searchPhrase: "banana", referenceType: "mood", confidence: 0.6,
    mappedTags: [],
    relatedTerms: ["yellow", "brown", "leather", "warm tone"] },
  { searchPhrase: "trashed jeans", referenceType: "search_reference", confidence: 0.9,
    mappedTags: ["streetwear", "independent"],
    relatedTerms: ["distressed denim", "destroyed denim", "ripped denim", "distressed jeans"] },
  { searchPhrase: "slub", referenceType: "fabric", confidence: 0.8,
    mappedTags: ["independent", "minimal"],
    relatedTerms: ["slub cotton", "textured tee", "slubby"] },
  { searchPhrase: "repaired jeans", referenceType: "search_reference", confidence: 0.9,
    mappedTags: ["archival", "independent"],
    relatedTerms: ["repaired", "patchwork", "mending", "reconstruction", "boro"] },
  // Silhouette-specific phrases: exact text matching outranks the expansion, so
  // "bootcut" returns bootcut jeans specifically, not every flare (ranking rule).
  { searchPhrase: "bootcut", referenceType: "silhouette", confidence: 0.9,
    mappedTags: [], relatedTerms: ["bootcut jeans"] },
  { searchPhrase: "bell bottom jeans", referenceType: "silhouette", confidence: 0.9,
    mappedTags: [], relatedTerms: ["bell bottom", "bell bottoms"] },
  // Base vocabulary → the brain's aesthetic axes (the seed catalog speaks these).
  { searchPhrase: "gorpcore", referenceType: "subculture", confidence: 0.9,
    mappedTags: ["gorp", "utilitarian"], relatedTerms: ["shell", "fleece", "trail"] },
  { searchPhrase: "workwear", referenceType: "aesthetic", confidence: 0.9,
    mappedTags: ["utilitarian"], relatedTerms: ["chore coat", "carpenter", "canvas", "double knee"] },
  { searchPhrase: "archive", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["archival"], relatedTerms: ["runway", "mainline", "vintage"] },
  { searchPhrase: "minimalist", referenceType: "aesthetic", confidence: 0.9,
    mappedTags: ["minimal", "tailored"], relatedTerms: ["clean", "column", "unstructured"] },
  { searchPhrase: "avant garde", referenceType: "aesthetic", confidence: 0.9,
    mappedTags: ["avant-garde"], relatedTerms: ["deconstructed", "asymmetric", "draped"] },
  { searchPhrase: "y2k", referenceType: "era", confidence: 0.8,
    mappedTags: ["statement", "streetwear"], relatedTerms: ["2000s", "low rise", "baby tee"] },
  // ---- asterisk-boost r1 additions ----
  { searchPhrase: "quiet luxury", referenceType: "aesthetic", confidence: 0.9,
    mappedTags: ["minimal", "tailored"],
    relatedTerms: ["the row", "loro piana", "cashmere", "camel coat", "unbranded"] },
  { searchPhrase: "old money", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["tailored", "minimal"],
    relatedTerms: ["blazer", "loafer", "tweed", "polo", "pleated trouser"] },
  { searchPhrase: "office siren", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["tailored", "seductive"],
    relatedTerms: ["pencil skirt", "square glasses", "fitted shirt", "pinstripe"] },
  { searchPhrase: "mob wife", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["seductive", "statement"],
    relatedTerms: ["fur coat", "leopard", "gold jewelry", "leather trench"] },
  { searchPhrase: "coquette", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["seductive", "statement"],
    relatedTerms: ["bow", "lace", "ribbon", "mary jane", "baby tee"] },
  { searchPhrase: "balletcore", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["seductive", "minimal"],
    relatedTerms: ["wrap top", "leg warmers", "ballet flat", "tulle", "bodysuit"] },
  { searchPhrase: "dark academia", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["tailored", "archival"],
    relatedTerms: ["tweed", "cardigan", "oxford", "pleated", "wool trouser"] },
  { searchPhrase: "techwear", referenceType: "subculture", confidence: 0.9,
    mappedTags: ["utilitarian", "avant-garde", "streetwear"],
    relatedTerms: ["acronym", "shell", "straps", "modular", "waterproof", "cargo"] },
  { searchPhrase: "opium", referenceType: "subculture", confidence: 0.8,
    mappedTags: ["avant-garde", "streetwear", "statement"],
    relatedTerms: ["rick owens", "leather pants", "platform boots", "distressed", "black"] },
  { searchPhrase: "blokecore", referenceType: "subculture", confidence: 0.8,
    mappedTags: ["streetwear", "archival"],
    relatedTerms: ["football jersey", "track jacket", "adidas", "vintage kit", "sambas"] },
  { searchPhrase: "normcore", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["minimal", "utilitarian"],
    relatedTerms: ["plain", "regular fit", "dad shoe", "fleece", "basic"] },
  { searchPhrase: "city boy", referenceType: "subculture", confidence: 0.8,
    mappedTags: ["streetwear", "minimal", "utilitarian"],
    relatedTerms: ["wide chino", "beams", "layered", "japanese", "workwear"] },
  { searchPhrase: "japanese denim", referenceType: "craft", confidence: 0.9,
    mappedTags: ["archival", "independent", "utilitarian"],
    relatedTerms: ["selvedge", "raw denim", "kapital", "evisu", "loopwheel", "repro"] },
  { searchPhrase: "military surplus", referenceType: "aesthetic", confidence: 0.9,
    mappedTags: ["utilitarian", "archival"],
    relatedTerms: ["m65", "field jacket", "fatigue", "cargo", "camo", "army"] },
  { searchPhrase: "heritage", referenceType: "aesthetic", confidence: 0.8,
    mappedTags: ["archival", "utilitarian", "tailored"],
    relatedTerms: ["waxed jacket", "chore coat", "red wing", "flannel", "made in usa"] },
  { searchPhrase: "clubwear", referenceType: "occasion", confidence: 0.8,
    mappedTags: ["seductive", "statement", "streetwear"],
    relatedTerms: ["mesh top", "metallic", "cutout", "mini skirt", "going out"] },
  { searchPhrase: "date night", referenceType: "occasion", confidence: 0.7,
    mappedTags: ["seductive", "tailored"],
    relatedTerms: ["slip dress", "silk", "heels", "fitted", "little black dress"] },
  { searchPhrase: "wedding guest", referenceType: "occasion", confidence: 0.7,
    mappedTags: ["tailored", "seductive"],
    relatedTerms: ["suit", "midi dress", "silk", "loafer", "double breasted"] },
  { searchPhrase: "festival", referenceType: "occasion", confidence: 0.7,
    mappedTags: ["statement", "streetwear", "independent"],
    relatedTerms: ["fringe", "denim shorts", "boots", "graphic", "crochet"] },
  { searchPhrase: "rainy day", referenceType: "occasion", confidence: 0.7,
    mappedTags: ["gorp", "utilitarian"],
    relatedTerms: ["waterproof", "shell", "goretex", "anorak", "boots"] },
  { searchPhrase: "winter fit", referenceType: "occasion", confidence: 0.7,
    mappedTags: ["gorp", "streetwear", "tailored"],
    relatedTerms: ["puffer", "wool coat", "fleece", "beanie", "layered"] },
  { searchPhrase: "summer linen", referenceType: "occasion", confidence: 0.8,
    mappedTags: ["minimal", "tailored"],
    relatedTerms: ["linen", "camp collar", "drawstring", "lightweight", "cream"] },
  { searchPhrase: "gym to street", referenceType: "occasion", confidence: 0.7,
    mappedTags: ["streetwear", "minimal"],
    relatedTerms: ["track pant", "zip hoodie", "runner", "jersey", "nylon short"] },
  { searchPhrase: "all black everything", referenceType: "palette", confidence: 0.9,
    mappedTags: ["avant-garde", "minimal", "seductive"],
    relatedTerms: ["black", "monochrome", "leather", "matte"] },
  { searchPhrase: "earth tones", referenceType: "palette", confidence: 0.8,
    mappedTags: ["gorp", "utilitarian", "minimal"],
    relatedTerms: ["olive", "brown", "tan", "sage", "rust"] },
  { searchPhrase: "neutrals", referenceType: "palette", confidence: 0.8,
    mappedTags: ["minimal", "tailored"],
    relatedTerms: ["beige", "cream", "grey", "tonal", "camel"] },
  { searchPhrase: "silver hardware", referenceType: "detail", confidence: 0.8,
    mappedTags: ["avant-garde", "statement"],
    relatedTerms: ["zips", "buckle", "chrome", "metal", "stud"] },
  { searchPhrase: "distressed leather", referenceType: "material", confidence: 0.9,
    mappedTags: ["avant-garde", "independent", "archival"],
    relatedTerms: ["cracked leather", "worn leather", "moto", "biker", "patina"] },
  { searchPhrase: "chunky knit", referenceType: "material", confidence: 0.9,
    mappedTags: ["minimal", "independent"],
    relatedTerms: ["cable knit", "fisherman", "heavy gauge", "hand knit", "mohair"] },
  { searchPhrase: "sheer layers", referenceType: "material", confidence: 0.8,
    mappedTags: ["seductive", "avant-garde"],
    relatedTerms: ["mesh", "chiffon", "translucent", "organza", "stocking"] },
  { searchPhrase: "big silhouette", referenceType: "fit", confidence: 0.8,
    mappedTags: ["avant-garde", "streetwear"],
    relatedTerms: ["oversized", "wide leg", "voluminous", "baggy", "cocoon"] },
  { searchPhrase: "tailored but relaxed", referenceType: "fit", confidence: 0.8,
    mappedTags: ["tailored", "minimal"],
    relatedTerms: ["unstructured blazer", "pleated trouser", "drape", "soft shoulder"] },
  { searchPhrase: "layering pieces", referenceType: "styling", confidence: 0.8,
    mappedTags: ["minimal", "utilitarian", "avant-garde"],
    relatedTerms: ["longline", "vest", "overshirt", "thermal", "base layer"] },
  { searchPhrase: "statement outerwear", referenceType: "styling", confidence: 0.8,
    mappedTags: ["statement", "avant-garde"],
    relatedTerms: ["long coat", "printed jacket", "colored fur", "metallic puffer"] },
  { searchPhrase: "grail", referenceType: "collector", confidence: 0.8,
    mappedTags: ["archival", "statement"],
    relatedTerms: ["rare", "deadstock", "limited", "sample", "runway piece"] },
  { searchPhrase: "starter archive piece", referenceType: "collector", confidence: 0.8,
    mappedTags: ["archival", "independent"],
    relatedTerms: ["mainline", "diffusion", "vintage designer", "entry point"] },
  { searchPhrase: "uniform dressing", referenceType: "styling", confidence: 0.8,
    mappedTags: ["minimal", "utilitarian", "tailored"],
    relatedTerms: ["capsule", "repeat outfit", "daily uniform", "essentials"] },
];
