// ASiLUM brain — LEXICON: maps non-clothing signals to aesthetic tag vectors.
// This is what lets the moodboard 'think' — turning a color, a music genre, a
// place, a mood word, or a texture into a fashion aesthetic reading.
//
// asterisk-boost r1: expanded ~50 → ~220 entries. Every entry is curated,
// deterministic taste arithmetic — weights are editorial judgements in the
// 10 canonical axes, capped at 0.9 so no single word owns a profile.

// Each entry is a partial tag vector (weights 0..1). Absent tags = 0.
export const LEXICON = {
  // --- colors ---
  black:      { 'AVANT-GARDE': 0.5, MINIMAL: 0.4, SEDUCTIVE: 0.3 },
  white:      { MINIMAL: 0.6, TAILORED: 0.3 },
  cream:      { MINIMAL: 0.5, TAILORED: 0.4 },
  ivory:      { MINIMAL: 0.5, TAILORED: 0.4, SEDUCTIVE: 0.2 },
  beige:      { MINIMAL: 0.6, TAILORED: 0.4 },
  tan:        { MINIMAL: 0.4, UTILITARIAN: 0.4, ARCHIVAL: 0.2 },
  camel:      { TAILORED: 0.6, MINIMAL: 0.4 },
  brown:      { ARCHIVAL: 0.4, UTILITARIAN: 0.4, MINIMAL: 0.2 },
  chocolate:  { ARCHIVAL: 0.4, TAILORED: 0.3, MINIMAL: 0.3 },
  grey:       { MINIMAL: 0.6, 'AVANT-GARDE': 0.2, TAILORED: 0.3 },
  gray:       { MINIMAL: 0.6, 'AVANT-GARDE': 0.2, TAILORED: 0.3 },
  charcoal:   { MINIMAL: 0.5, TAILORED: 0.4, 'AVANT-GARDE': 0.3 },
  navy:       { TAILORED: 0.6, MINIMAL: 0.3, UTILITARIAN: 0.2 },
  olive:      { UTILITARIAN: 0.7, GORP: 0.5, STREETWEAR: 0.3 },
  khaki:      { UTILITARIAN: 0.6, GORP: 0.3, MINIMAL: 0.2 },
  sage:       { MINIMAL: 0.4, GORP: 0.4 },
  forest:     { GORP: 0.5, UTILITARIAN: 0.4 },
  crimson:    { SEDUCTIVE: 0.6, STATEMENT: 0.5 },
  red:        { STATEMENT: 0.5, SEDUCTIVE: 0.5 },
  burgundy:   { SEDUCTIVE: 0.5, TAILORED: 0.4, ARCHIVAL: 0.2 },
  oxblood:    { SEDUCTIVE: 0.5, ARCHIVAL: 0.4, 'AVANT-GARDE': 0.2 },
  pink:       { SEDUCTIVE: 0.5, STATEMENT: 0.4 },
  fuchsia:    { STATEMENT: 0.6, SEDUCTIVE: 0.4 },
  purple:     { STATEMENT: 0.4, SEDUCTIVE: 0.3, INDEPENDENT: 0.3 },
  lavender:   { SEDUCTIVE: 0.3, MINIMAL: 0.3, STATEMENT: 0.2 },
  neon:       { STATEMENT: 0.7, STREETWEAR: 0.5 },
  orange:     { STATEMENT: 0.5, GORP: 0.4, STREETWEAR: 0.3 },
  yellow:     { STATEMENT: 0.5, STREETWEAR: 0.3 },
  gold:       { SEDUCTIVE: 0.5, STATEMENT: 0.5 },
  silver:     { STATEMENT: 0.4, 'AVANT-GARDE': 0.4 },
  earth:      { GORP: 0.6, UTILITARIAN: 0.5, ARCHIVAL: 0.3 },
  pastel:     { MINIMAL: 0.4, SEDUCTIVE: 0.3 },
  monochrome: { MINIMAL: 0.7, 'AVANT-GARDE': 0.4 },
  tonal:      { MINIMAL: 0.6, TAILORED: 0.3 },

  // --- materials / textures ---
  leather:    { SEDUCTIVE: 0.5, STATEMENT: 0.4 },
  suede:      { ARCHIVAL: 0.4, SEDUCTIVE: 0.3, TAILORED: 0.3 },
  patent:     { SEDUCTIVE: 0.6, STATEMENT: 0.5 },
  nylon:      { UTILITARIAN: 0.7, GORP: 0.5 },
  ripstop:    { UTILITARIAN: 0.7, GORP: 0.6 },
  cordura:    { UTILITARIAN: 0.7, GORP: 0.6 },
  wool:       { TAILORED: 0.6, MINIMAL: 0.4 },
  cashmere:   { TAILORED: 0.6, MINIMAL: 0.5, SEDUCTIVE: 0.3 },
  mohair:     { INDEPENDENT: 0.5, 'AVANT-GARDE': 0.4, ARCHIVAL: 0.3 },
  angora:     { SEDUCTIVE: 0.4, INDEPENDENT: 0.3 },
  silk:       { SEDUCTIVE: 0.6, TAILORED: 0.4 },
  satin:      { SEDUCTIVE: 0.7, STATEMENT: 0.3 },
  lace:       { SEDUCTIVE: 0.7, STATEMENT: 0.3, ARCHIVAL: 0.2 },
  velvet:     { SEDUCTIVE: 0.6, ARCHIVAL: 0.3, STATEMENT: 0.3 },
  chiffon:    { SEDUCTIVE: 0.5, MINIMAL: 0.2 },
  tulle:      { STATEMENT: 0.5, SEDUCTIVE: 0.4, 'AVANT-GARDE': 0.3 },
  organza:    { 'AVANT-GARDE': 0.4, SEDUCTIVE: 0.4, STATEMENT: 0.3 },
  denim:      { STREETWEAR: 0.4, ARCHIVAL: 0.4, UTILITARIAN: 0.3 },
  selvedge:   { ARCHIVAL: 0.5, INDEPENDENT: 0.4, UTILITARIAN: 0.3 },
  corduroy:   { ARCHIVAL: 0.5, INDEPENDENT: 0.4 },
  tweed:      { TAILORED: 0.6, ARCHIVAL: 0.4 },
  flannel:    { INDEPENDENT: 0.4, UTILITARIAN: 0.4, ARCHIVAL: 0.3 },
  canvas:     { UTILITARIAN: 0.6, ARCHIVAL: 0.3 },
  moleskin:   { UTILITARIAN: 0.5, ARCHIVAL: 0.4, TAILORED: 0.3 },
  jersey:     { MINIMAL: 0.4, STREETWEAR: 0.3 },
  fleece:     { GORP: 0.7, STREETWEAR: 0.3 },
  sherpa:     { GORP: 0.6, STREETWEAR: 0.3 },
  mesh:       { STREETWEAR: 0.4, UTILITARIAN: 0.4 },
  knit:       { MINIMAL: 0.4, TAILORED: 0.3, INDEPENDENT: 0.2 },
  crochet:    { INDEPENDENT: 0.6, ARCHIVAL: 0.3 },
  shearling:  { ARCHIVAL: 0.4, SEDUCTIVE: 0.3, GORP: 0.3 },
  fur:        { STATEMENT: 0.6, SEDUCTIVE: 0.5 },
  goretex:    { GORP: 0.8, UTILITARIAN: 0.6 },
  'gore-tex': { GORP: 0.8, UTILITARIAN: 0.6 },
  distressed: { INDEPENDENT: 0.6, ARCHIVAL: 0.5 },
  waxed:      { UTILITARIAN: 0.6, ARCHIVAL: 0.4 },
  coated:     { 'AVANT-GARDE': 0.4, UTILITARIAN: 0.4 },
  raw:        { INDEPENDENT: 0.5, 'AVANT-GARDE': 0.4, UTILITARIAN: 0.3 },
  washed:     { ARCHIVAL: 0.4, INDEPENDENT: 0.4, STREETWEAR: 0.3 },
  faded:      { ARCHIVAL: 0.5, INDEPENDENT: 0.4 },
  patchwork:  { INDEPENDENT: 0.6, ARCHIVAL: 0.5 },
  boro:       { INDEPENDENT: 0.7, ARCHIVAL: 0.6 },
  sashiko:    { INDEPENDENT: 0.7, ARCHIVAL: 0.5 },

  // --- garment / construction / fit language ---
  gorp:       { GORP: 0.9, UTILITARIAN: 0.5 },
  shell:      { GORP: 0.6, UTILITARIAN: 0.5 },
  hardshell:  { GORP: 0.7, UTILITARIAN: 0.5 },
  softshell:  { GORP: 0.6, UTILITARIAN: 0.4 },
  anorak:     { GORP: 0.6, UTILITARIAN: 0.5, ARCHIVAL: 0.2 },
  parka:      { GORP: 0.5, UTILITARIAN: 0.5, STREETWEAR: 0.2 },
  puffer:     { GORP: 0.6, STREETWEAR: 0.5 },
  windbreaker:{ GORP: 0.5, STREETWEAR: 0.4, ARCHIVAL: 0.2 },
  cargo:      { UTILITARIAN: 0.7, STREETWEAR: 0.4 },
  carpenter:  { UTILITARIAN: 0.7, STREETWEAR: 0.4, ARCHIVAL: 0.3 },
  'double knee': { UTILITARIAN: 0.8, STREETWEAR: 0.3 },
  chore:      { UTILITARIAN: 0.7, ARCHIVAL: 0.4, INDEPENDENT: 0.2 },
  coverall:   { UTILITARIAN: 0.8, ARCHIVAL: 0.3 },
  fatigue:    { UTILITARIAN: 0.7, ARCHIVAL: 0.4 },
  camo:       { UTILITARIAN: 0.6, STREETWEAR: 0.5, GORP: 0.3 },
  tactical:   { UTILITARIAN: 0.8, GORP: 0.5 },
  'multi pocket': { UTILITARIAN: 0.7, GORP: 0.4 },
  hoodie:     { STREETWEAR: 0.6 },
  crewneck:   { STREETWEAR: 0.4, MINIMAL: 0.3 },
  varsity:    { STREETWEAR: 0.6, ARCHIVAL: 0.3 },
  jersey_tee: { STREETWEAR: 0.5 },
  'baby tee': { STATEMENT: 0.5, SEDUCTIVE: 0.4, STREETWEAR: 0.3 },
  'low rise': { STATEMENT: 0.5, SEDUCTIVE: 0.4, STREETWEAR: 0.3 },
  baggy:      { STREETWEAR: 0.6, INDEPENDENT: 0.3 },
  oversized:  { STREETWEAR: 0.5, 'AVANT-GARDE': 0.4 },
  boxy:       { MINIMAL: 0.4, 'AVANT-GARDE': 0.4 },
  cropped:    { STATEMENT: 0.4, STREETWEAR: 0.4, SEDUCTIVE: 0.3 },
  slouchy:    { MINIMAL: 0.4, INDEPENDENT: 0.4 },
  draped:     { 'AVANT-GARDE': 0.6, SEDUCTIVE: 0.3, MINIMAL: 0.3 },
  asymmetric: { 'AVANT-GARDE': 0.7, INDEPENDENT: 0.4 },
  deconstructed: { 'AVANT-GARDE': 0.8, ARCHIVAL: 0.5, INDEPENDENT: 0.4 },
  raglan:     { ARCHIVAL: 0.3, STREETWEAR: 0.3, UTILITARIAN: 0.2 },
  'drop shoulder': { STREETWEAR: 0.4, MINIMAL: 0.3, 'AVANT-GARDE': 0.2 },
  pleated:    { TAILORED: 0.6, ARCHIVAL: 0.3, MINIMAL: 0.2 },
  pinstripe:  { TAILORED: 0.8 },
  'double breasted': { TAILORED: 0.8, STATEMENT: 0.3 },
  unstructured: { TAILORED: 0.5, MINIMAL: 0.5 },
  bespoke:    { TAILORED: 0.8, ARCHIVAL: 0.3 },
  corset:     { SEDUCTIVE: 0.8, STATEMENT: 0.4 },
  bustier:    { SEDUCTIVE: 0.8, STATEMENT: 0.4 },
  slip:       { SEDUCTIVE: 0.6, MINIMAL: 0.4 },
  bodycon:    { SEDUCTIVE: 0.8, STATEMENT: 0.4 },
  sheer:      { SEDUCTIVE: 0.6, 'AVANT-GARDE': 0.4 },
  cutout:     { SEDUCTIVE: 0.6, STATEMENT: 0.5 },
  halter:     { SEDUCTIVE: 0.5, STATEMENT: 0.3 },
  turtleneck: { MINIMAL: 0.5, TAILORED: 0.4 },
  'mock neck': { MINIMAL: 0.5, TAILORED: 0.3 },
  trench:     { TAILORED: 0.5, ARCHIVAL: 0.4, MINIMAL: 0.3 },
  overcoat:   { TAILORED: 0.6, MINIMAL: 0.4 },
  bomber:     { STREETWEAR: 0.5, ARCHIVAL: 0.4, UTILITARIAN: 0.3 },
  moto:       { SEDUCTIVE: 0.4, STATEMENT: 0.4, STREETWEAR: 0.3 },
  biker:      { SEDUCTIVE: 0.4, STATEMENT: 0.4, INDEPENDENT: 0.3 },
  western:    { ARCHIVAL: 0.5, INDEPENDENT: 0.4, STATEMENT: 0.3 },
  workboot:   { UTILITARIAN: 0.7, ARCHIVAL: 0.3 },
  loafer:     { TAILORED: 0.6, MINIMAL: 0.3, ARCHIVAL: 0.2 },
  derby:      { TAILORED: 0.6, ARCHIVAL: 0.3 },
  'square toe': { 'AVANT-GARDE': 0.4, TAILORED: 0.4, SEDUCTIVE: 0.3 },
  stiletto:   { SEDUCTIVE: 0.7, STATEMENT: 0.4 },
  platform:   { STATEMENT: 0.6, 'AVANT-GARDE': 0.3, STREETWEAR: 0.3 },
  'chunky sneaker': { STREETWEAR: 0.6, STATEMENT: 0.4 },
  'trail runner': { GORP: 0.8, STREETWEAR: 0.4 },
  'hiking boot': { GORP: 0.8, UTILITARIAN: 0.4 },
  tabi:       { 'AVANT-GARDE': 0.8, ARCHIVAL: 0.4, INDEPENDENT: 0.4 },
  harness:    { 'AVANT-GARDE': 0.5, UTILITARIAN: 0.4, SEDUCTIVE: 0.3 },
  'tote bag': { MINIMAL: 0.4, UTILITARIAN: 0.4 },
  crossbody:  { UTILITARIAN: 0.5, STREETWEAR: 0.4 },
  balaclava:  { STREETWEAR: 0.5, 'AVANT-GARDE': 0.4, GORP: 0.3 },
  beanie:     { STREETWEAR: 0.5, GORP: 0.3, INDEPENDENT: 0.2 },
  trucker:    { STREETWEAR: 0.4, ARCHIVAL: 0.3, UTILITARIAN: 0.3 },
  vintage:    { ARCHIVAL: 0.7, INDEPENDENT: 0.3 },
  archive:    { ARCHIVAL: 0.9, 'AVANT-GARDE': 0.4 },
  runway:     { STATEMENT: 0.6, 'AVANT-GARDE': 0.5, ARCHIVAL: 0.4 },
  mainline:   { ARCHIVAL: 0.6, 'AVANT-GARDE': 0.4 },
  deadstock:  { ARCHIVAL: 0.7, INDEPENDENT: 0.4, STREETWEAR: 0.3 },
  sample:     { ARCHIVAL: 0.5, 'AVANT-GARDE': 0.4, INDEPENDENT: 0.3 },
  grail:      { ARCHIVAL: 0.6, STATEMENT: 0.4, INDEPENDENT: 0.3 },
  reissue:    { ARCHIVAL: 0.6, STATEMENT: 0.2 },
  collab:     { STREETWEAR: 0.5, STATEMENT: 0.4 },
  graphic:    { STREETWEAR: 0.5, STATEMENT: 0.5 },
  logo:       { STREETWEAR: 0.5, STATEMENT: 0.4 },
  blank:      { MINIMAL: 0.6, STREETWEAR: 0.3 },
  heavyweight:{ STREETWEAR: 0.4, MINIMAL: 0.3, UTILITARIAN: 0.3 },
  layered:    { 'AVANT-GARDE': 0.4, GORP: 0.4, STREETWEAR: 0.3 },
  uniform:    { MINIMAL: 0.5, UTILITARIAN: 0.5, TAILORED: 0.3 },

  // --- moods / aesthetic words ---
  techwear:   { UTILITARIAN: 0.8, STREETWEAR: 0.5, 'AVANT-GARDE': 0.4 },
  'mob wife': { SEDUCTIVE: 0.8, STATEMENT: 0.7, TAILORED: 0.3 },
  opium:      { 'AVANT-GARDE': 0.6, STATEMENT: 0.6, STREETWEAR: 0.5 },
  quiet:      { MINIMAL: 0.8, TAILORED: 0.6 },
  loud:       { STATEMENT: 0.8, STREETWEAR: 0.4 },
  grunge:     { INDEPENDENT: 0.6, STREETWEAR: 0.5, ARCHIVAL: 0.4 },
  romantic:   { SEDUCTIVE: 0.6, ARCHIVAL: 0.3, INDEPENDENT: 0.2 },
  gothic:     { 'AVANT-GARDE': 0.6, SEDUCTIVE: 0.5, STATEMENT: 0.4 },
  goth:       { 'AVANT-GARDE': 0.6, SEDUCTIVE: 0.5, STATEMENT: 0.4 },
  punk:       { INDEPENDENT: 0.7, STATEMENT: 0.6, STREETWEAR: 0.3 },
  preppy:     { TAILORED: 0.6, MINIMAL: 0.3, ARCHIVAL: 0.3 },
  ivy:        { TAILORED: 0.7, ARCHIVAL: 0.5, MINIMAL: 0.3 },
  mod:        { TAILORED: 0.6, MINIMAL: 0.4, ARCHIVAL: 0.4 },
  bohemian:   { INDEPENDENT: 0.6, ARCHIVAL: 0.4, SEDUCTIVE: 0.3 },
  boho:       { INDEPENDENT: 0.6, ARCHIVAL: 0.4, SEDUCTIVE: 0.3 },
  clean:      { MINIMAL: 0.7, TAILORED: 0.4 },
  sleek:      { MINIMAL: 0.6, SEDUCTIVE: 0.4, TAILORED: 0.4 },
  polished:   { TAILORED: 0.7, MINIMAL: 0.4, SEDUCTIVE: 0.2 },
  rugged:     { UTILITARIAN: 0.6, GORP: 0.5, ARCHIVAL: 0.3 },
  utility:    { UTILITARIAN: 0.8, GORP: 0.4 },
  workwear:   { UTILITARIAN: 0.8, ARCHIVAL: 0.3 },
  military:   { UTILITARIAN: 0.7, ARCHIVAL: 0.4 },
  nautical:   { TAILORED: 0.4, ARCHIVAL: 0.4, UTILITARIAN: 0.3 },
  sporty:     { STREETWEAR: 0.6, UTILITARIAN: 0.3, GORP: 0.3 },
  athleisure: { STREETWEAR: 0.6, MINIMAL: 0.3 },
  glam:       { SEDUCTIVE: 0.7, STATEMENT: 0.6 },
  evening:    { SEDUCTIVE: 0.6, TAILORED: 0.5, STATEMENT: 0.3 },
  cyber:      { 'AVANT-GARDE': 0.6, STATEMENT: 0.5, STREETWEAR: 0.4 },
  futuristic: { 'AVANT-GARDE': 0.7, STATEMENT: 0.4, UTILITARIAN: 0.3 },
  dystopian:  { 'AVANT-GARDE': 0.6, UTILITARIAN: 0.5, INDEPENDENT: 0.3 },
  brutalist:  { 'AVANT-GARDE': 0.6, MINIMAL: 0.5, UTILITARIAN: 0.3 },
  ethereal:   { SEDUCTIVE: 0.5, 'AVANT-GARDE': 0.4, MINIMAL: 0.3 },
  nostalgic:  { ARCHIVAL: 0.6, INDEPENDENT: 0.3 },
  retro:      { ARCHIVAL: 0.6, STATEMENT: 0.3, STREETWEAR: 0.2 },
  minimalist: { MINIMAL: 0.9, TAILORED: 0.4 },
  maximalist: { STATEMENT: 0.8, SEDUCTIVE: 0.3, 'AVANT-GARDE': 0.3 },
  eclectic:   { INDEPENDENT: 0.6, STATEMENT: 0.4, ARCHIVAL: 0.3 },
  effortless: { MINIMAL: 0.5, INDEPENDENT: 0.4 },
  elevated:   { TAILORED: 0.5, MINIMAL: 0.5 },
  edgy:       { 'AVANT-GARDE': 0.5, STATEMENT: 0.5, INDEPENDENT: 0.3 },
  moody:      { 'AVANT-GARDE': 0.4, SEDUCTIVE: 0.4, INDEPENDENT: 0.3 },
  cozy:       { MINIMAL: 0.4, GORP: 0.4, INDEPENDENT: 0.2 },
  outdoorsy:  { GORP: 0.8, UTILITARIAN: 0.4 },

  // --- music ---
  ambient:    { MINIMAL: 0.6, 'AVANT-GARDE': 0.3 },
  drill:      { STREETWEAR: 0.7, STATEMENT: 0.5 },
  rap:        { STREETWEAR: 0.7, STATEMENT: 0.4 },
  'hip hop':  { STREETWEAR: 0.7, STATEMENT: 0.4 },
  trap:       { STREETWEAR: 0.6, STATEMENT: 0.5 },
  rage:       { STREETWEAR: 0.6, 'AVANT-GARDE': 0.5, STATEMENT: 0.5 },
  jazz:       { TAILORED: 0.6, ARCHIVAL: 0.4, SEDUCTIVE: 0.3 },
  soul:       { TAILORED: 0.5, SEDUCTIVE: 0.4, ARCHIVAL: 0.3 },
  funk:       { STATEMENT: 0.6, SEDUCTIVE: 0.4, ARCHIVAL: 0.3 },
  disco:      { SEDUCTIVE: 0.6, STATEMENT: 0.6 },
  hyperpop:   { STATEMENT: 0.7, 'AVANT-GARDE': 0.5, STREETWEAR: 0.4 },
  techno:     { UTILITARIAN: 0.6, 'AVANT-GARDE': 0.5, MINIMAL: 0.4 },
  house:      { STREETWEAR: 0.4, STATEMENT: 0.4, SEDUCTIVE: 0.3 },
  indie:      { INDEPENDENT: 0.7, ARCHIVAL: 0.3 },
  shoegaze:   { INDEPENDENT: 0.6, 'AVANT-GARDE': 0.4, MINIMAL: 0.3 },
  emo:        { INDEPENDENT: 0.6, STREETWEAR: 0.4, STATEMENT: 0.3 },
  metal:      { STATEMENT: 0.6, INDEPENDENT: 0.5, 'AVANT-GARDE': 0.3 },
  rock:       { INDEPENDENT: 0.5, STATEMENT: 0.4, ARCHIVAL: 0.3 },
  classical:  { TAILORED: 0.6, MINIMAL: 0.4, ARCHIVAL: 0.3 },
  rnb:        { SEDUCTIVE: 0.6, STREETWEAR: 0.4 },
  'r&b':      { SEDUCTIVE: 0.6, STREETWEAR: 0.4 },
  country:    { ARCHIVAL: 0.5, UTILITARIAN: 0.4, INDEPENDENT: 0.3 },
  folk:       { INDEPENDENT: 0.5, ARCHIVAL: 0.4, GORP: 0.2 },

  // --- places ---
  berlin:     { UTILITARIAN: 0.6, 'AVANT-GARDE': 0.5, MINIMAL: 0.4 },
  tokyo:      { 'AVANT-GARDE': 0.5, STREETWEAR: 0.5, INDEPENDENT: 0.4 },
  milan:      { TAILORED: 0.7, SEDUCTIVE: 0.5 },
  paris:      { TAILORED: 0.6, 'AVANT-GARDE': 0.5, SEDUCTIVE: 0.4 },
  london:     { INDEPENDENT: 0.5, STATEMENT: 0.4, TAILORED: 0.4 },
  'new york': { STREETWEAR: 0.5, TAILORED: 0.4, MINIMAL: 0.4 },
  brooklyn:   { INDEPENDENT: 0.5, STREETWEAR: 0.5 },
  la:         { STREETWEAR: 0.5, STATEMENT: 0.4, SEDUCTIVE: 0.3 },
  'los angeles': { STREETWEAR: 0.5, STATEMENT: 0.4, SEDUCTIVE: 0.3 },
  miami:      { SEDUCTIVE: 0.6, STATEMENT: 0.5 },
  seoul:      { STREETWEAR: 0.6, MINIMAL: 0.4, STATEMENT: 0.3 },
  copenhagen: { MINIMAL: 0.6, INDEPENDENT: 0.4, STATEMENT: 0.3 },
  stockholm:  { MINIMAL: 0.7, TAILORED: 0.4 },
  antwerp:    { 'AVANT-GARDE': 0.7, INDEPENDENT: 0.5, ARCHIVAL: 0.4 },
  vienna:     { TAILORED: 0.5, ARCHIVAL: 0.4, 'AVANT-GARDE': 0.3 },
  osaka:      { ARCHIVAL: 0.5, INDEPENDENT: 0.5, STREETWEAR: 0.4 },
  kyoto:      { MINIMAL: 0.5, ARCHIVAL: 0.5, INDEPENDENT: 0.3 },
  alps:       { GORP: 0.8, UTILITARIAN: 0.5 },
  patagonia_region: { GORP: 0.8, UTILITARIAN: 0.4 },
  desert:     { UTILITARIAN: 0.4, GORP: 0.4, MINIMAL: 0.3 },
  coastal:    { MINIMAL: 0.4, TAILORED: 0.3, GORP: 0.2 },

  // --- garment specifics (asterisk-boost r2: measured misses) ---
  'gurkha':    { TAILORED: 0.7, ARCHIVAL: 0.4 },
  'balmacaan': { TAILORED: 0.6, MINIMAL: 0.4, ARCHIVAL: 0.3 },
  'duffle':    { ARCHIVAL: 0.5, TAILORED: 0.4, UTILITARIAN: 0.3 },
  'loden':     { TAILORED: 0.5, ARCHIVAL: 0.4, UTILITARIAN: 0.3 },
  'harrington':{ ARCHIVAL: 0.5, MINIMAL: 0.3, STREETWEAR: 0.3 },
  'souvenir jacket': { ARCHIVAL: 0.6, STATEMENT: 0.5, STREETWEAR: 0.3 },
  'sukajan':   { ARCHIVAL: 0.6, STATEMENT: 0.5, INDEPENDENT: 0.4 },
  'noragi':    { INDEPENDENT: 0.6, ARCHIVAL: 0.5, MINIMAL: 0.3 },
  'hanten':    { INDEPENDENT: 0.6, ARCHIVAL: 0.5 },
  'smock':     { UTILITARIAN: 0.5, INDEPENDENT: 0.4, ARCHIVAL: 0.3 },
  'boiler suit': { UTILITARIAN: 0.8, ARCHIVAL: 0.3 },
  'boilersuit': { UTILITARIAN: 0.8, ARCHIVAL: 0.3 },
  'jumpsuit':  { UTILITARIAN: 0.6, STATEMENT: 0.3, 'AVANT-GARDE': 0.2 },
  'shacket':   { UTILITARIAN: 0.5, STREETWEAR: 0.4, MINIMAL: 0.2 },
  'gilet':     { UTILITARIAN: 0.5, GORP: 0.5, TAILORED: 0.2 },
  'tank':      { STREETWEAR: 0.4, MINIMAL: 0.3, SEDUCTIVE: 0.2 },
  'muscle tee':{ STREETWEAR: 0.5, SEDUCTIVE: 0.3 },
  'henley':    { MINIMAL: 0.4, ARCHIVAL: 0.4, UTILITARIAN: 0.2 },
  'rugby':     { ARCHIVAL: 0.5, STREETWEAR: 0.4, TAILORED: 0.2 },
  'cuban collar': { ARCHIVAL: 0.5, SEDUCTIVE: 0.4, MINIMAL: 0.2 },
  'track jacket': { STREETWEAR: 0.6, ARCHIVAL: 0.3 },
  'football jersey': { STREETWEAR: 0.6, ARCHIVAL: 0.4 },

  // --- technical materials (asterisk-boost r2) ---
  'dyneema':   { GORP: 0.8, UTILITARIAN: 0.6, 'AVANT-GARDE': 0.2 },
  'pertex':    { GORP: 0.8, UTILITARIAN: 0.5 },
  'polartec':  { GORP: 0.8, UTILITARIAN: 0.4 },
  'primaloft': { GORP: 0.7, UTILITARIAN: 0.4 },
  'ventile':   { GORP: 0.6, UTILITARIAN: 0.5, ARCHIVAL: 0.3 },
  'kevlar':    { UTILITARIAN: 0.7, 'AVANT-GARDE': 0.3 },
  'merino':    { GORP: 0.5, MINIMAL: 0.4, TAILORED: 0.3 },
  'alpaca':    { TAILORED: 0.5, MINIMAL: 0.4, INDEPENDENT: 0.3 },
  'lyocell':   { MINIMAL: 0.5, TAILORED: 0.3 },
  'cupro':     { MINIMAL: 0.5, SEDUCTIVE: 0.3, TAILORED: 0.3 },
  'loopwheel': { ARCHIVAL: 0.7, INDEPENDENT: 0.5, UTILITARIAN: 0.3 },
  'garment dyed': { INDEPENDENT: 0.5, ARCHIVAL: 0.4, MINIMAL: 0.3 },
  'acid wash': { STREETWEAR: 0.5, ARCHIVAL: 0.4, STATEMENT: 0.3 },
  'stone wash': { ARCHIVAL: 0.5, STREETWEAR: 0.4 },
  'enzyme wash': { ARCHIVAL: 0.4, MINIMAL: 0.3 },
  'vegetable tanned': { ARCHIVAL: 0.6, INDEPENDENT: 0.4, UTILITARIAN: 0.3 },

  // --- mood words (asterisk-boost r2) ---
  'demure':    { MINIMAL: 0.6, TAILORED: 0.5, SEDUCTIVE: 0.2 },
  'feral':     { INDEPENDENT: 0.6, 'AVANT-GARDE': 0.5, STATEMENT: 0.4 },
  'unhinged':  { STATEMENT: 0.6, 'AVANT-GARDE': 0.5, INDEPENDENT: 0.4 },
  'serving':   { STATEMENT: 0.6, SEDUCTIVE: 0.5 },
  'clean girl':{ MINIMAL: 0.7, SEDUCTIVE: 0.3 },
  'that girl': { MINIMAL: 0.6, STREETWEAR: 0.3, SEDUCTIVE: 0.3 },
  'off duty':  { MINIMAL: 0.5, STREETWEAR: 0.4, INDEPENDENT: 0.3 },
  'dressed down': { MINIMAL: 0.5, STREETWEAR: 0.4 },
  'anti-fit':  { 'AVANT-GARDE': 0.6, MINIMAL: 0.4, INDEPENDENT: 0.3 },
  'anti fit':  { 'AVANT-GARDE': 0.6, MINIMAL: 0.4, INDEPENDENT: 0.3 },
  'wabi sabi': { INDEPENDENT: 0.6, MINIMAL: 0.5, ARCHIVAL: 0.4 },
  'shibui':    { MINIMAL: 0.7, ARCHIVAL: 0.4, INDEPENDENT: 0.3 },
  'iki':       { MINIMAL: 0.5, TAILORED: 0.4, INDEPENDENT: 0.3 },
  'sprezzatura': { TAILORED: 0.7, INDEPENDENT: 0.4, ARCHIVAL: 0.3 },
  'insouciant': { INDEPENDENT: 0.5, MINIMAL: 0.4, SEDUCTIVE: 0.3 },
  'louche':    { SEDUCTIVE: 0.6, INDEPENDENT: 0.4, TAILORED: 0.3 },
  'severe':    { 'AVANT-GARDE': 0.6, MINIMAL: 0.5, TAILORED: 0.3 },
  'stylish':   { TAILORED: 0.4, MINIMAL: 0.3, STATEMENT: 0.3 },
  'airport':   { STREETWEAR: 0.5, MINIMAL: 0.4, UTILITARIAN: 0.3 },
  'beach':     { MINIMAL: 0.4, SEDUCTIVE: 0.3, INDEPENDENT: 0.2 },
  'wedding':   { TAILORED: 0.6, SEDUCTIVE: 0.4, STATEMENT: 0.2 },
  'gallery':   { 'AVANT-GARDE': 0.5, MINIMAL: 0.4, TAILORED: 0.3 },
  'rave':      { STATEMENT: 0.6, STREETWEAR: 0.5, 'AVANT-GARDE': 0.3 },
  'business':  { TAILORED: 0.7, MINIMAL: 0.4 },
  'casual':    { MINIMAL: 0.4, STREETWEAR: 0.4 },
  'formal':    { TAILORED: 0.8, SEDUCTIVE: 0.2 },
  'fun':       { STATEMENT: 0.5, SEDUCTIVE: 0.3, INDEPENDENT: 0.2 },
  'ski':       { GORP: 0.7, STATEMENT: 0.3 },
  'lodge':     { GORP: 0.5, ARCHIVAL: 0.4, TAILORED: 0.2 },
  'dinner':    { TAILORED: 0.6, SEDUCTIVE: 0.4 },
  'cocktail':  { SEDUCTIVE: 0.6, TAILORED: 0.5 },
  'brunch':    { MINIMAL: 0.4, TAILORED: 0.3, SEDUCTIVE: 0.2 },
  'office':    { TAILORED: 0.7, MINIMAL: 0.4 },
  'cunty':     { SEDUCTIVE: 0.7, STATEMENT: 0.5 },
  'piece dyed':{ MINIMAL: 0.4, INDEPENDENT: 0.3, ARCHIVAL: 0.3 },

  // --- eras as words ---
  seventies:  { SEDUCTIVE: 0.5, INDEPENDENT: 0.4, ARCHIVAL: 0.3 },
  eighties:   { STATEMENT: 0.6, SEDUCTIVE: 0.4, ARCHIVAL: 0.2 },
  nineties:   { MINIMAL: 0.5, ARCHIVAL: 0.5, STREETWEAR: 0.3 },
  y2k:        { STATEMENT: 0.6, STREETWEAR: 0.5 },
  '2000s':    { STATEMENT: 0.5, STREETWEAR: 0.5 },
  '2010s':    { STREETWEAR: 0.6, STATEMENT: 0.3, MINIMAL: 0.2 },
  millennium: { STATEMENT: 0.5, STREETWEAR: 0.4 },
};

// Resolve a single free-text token to its partial tag vector, or null.
export function lexiconVector(token) {
  const entry = LEXICON[String(token || '').trim().toLowerCase()];
  return entry ? { ...entry } : null;
}
