export const WIKIMEDIA_LANGUAGES = Object.freeze(["en", "fr", "it", "de", "es", "pt", "ja", "ko", "zh", "ar"]);

export const WIKIPEDIA_DISCOVERY_SOURCES = Object.freeze([
  { key: "asilum-career-registry", label: "ASILUM sourced career registry", type: "internal_registry", url: "internal://lib/people/careers.data.json", region: "global", seasonOrDate: "continuing", enabled: true },
  { key: "global-major-names-registry", label: "Reviewed global major-name coverage registry", type: "internal_registry", url: "internal://data/fashion-coverage-registry.json", region: "global", seasonOrDate: "continuing", enabled: true },
  { key: "enwiki-list-fashion-designers", label: "English Wikipedia list of fashion designers by nationality", type: "wikipedia_list", url: "https://en.wikipedia.org/wiki/List_of_fashion_designers", region: "global", seasonOrDate: "continuing", enabled: true, language: "en", title: "List of fashion designers" },
  { key: "wikidata-fashion-designers", label: "Wikidata fashion-designer candidates", type: "wikidata", url: "https://query.wikidata.org/", region: "global", seasonOrDate: "continuing", enabled: true, classQid: "Q3501317" },
  { key: "wikidata-fashion-houses", label: "Wikidata fashion-house candidates", type: "wikidata", url: "https://query.wikidata.org/", region: "global", seasonOrDate: "continuing", enabled: true, classQid: "Q1941779" },
  { key: "wikidata-language-only-designers", label: "Wikidata designers with French Wikipedia coverage and no English article", type: "wikidata", url: "https://query.wikidata.org/", region: "global", seasonOrDate: "continuing", enabled: true, classQid: "Q3501317", language: "fr", requireNoEnglish: true },
  { key: "enwiki-fashion-designers", label: "English Wikipedia fashion designers", type: "wikipedia_category", url: "https://en.wikipedia.org/wiki/Category:Fashion_designers", region: "global", seasonOrDate: "continuing", enabled: true, language: "en", category: "Category:Fashion designers" },
  { key: "enwiki-fashion-houses", label: "English Wikipedia fashion houses", type: "wikipedia_category", url: "https://en.wikipedia.org/wiki/Category:Fashion_houses", region: "global", seasonOrDate: "continuing", enabled: true, language: "en", category: "Category:Fashion houses" },
  ...[
    ["american", "American", "North America"],
    ["canadian", "Canadian", "North America"],
    ["italian", "Italian", "Europe"],
    ["french", "French", "Europe"],
    ["british", "British", "Europe"],
    ["spanish", "Spanish", "Europe"],
    ["belgian", "Belgian", "Europe"],
    ["dutch", "Dutch", "Europe"],
    ["german", "German", "Europe"],
    ["portuguese", "Portuguese", "Europe"],
    ["greek", "Greek", "Europe"],
    ["scandinavian", "Scandinavian", "Europe"],
    ["african", "African", "Africa"],
    ["nigerian", "Nigerian", "Africa"],
    ["south-african", "South African", "Africa"],
    ["japanese", "Japanese", "East Asia"],
    ["chinese", "Chinese", "East Asia"],
    ["south-korean", "South Korean", "East Asia"],
    ["indian", "Indian", "South Asia"],
    ["pakistani", "Pakistani", "South Asia"],
    ["brazilian", "Brazilian", "Latin America and the Caribbean"],
    ["colombian", "Colombian", "Latin America and the Caribbean"],
    ["mexican", "Mexican", "Latin America and the Caribbean"],
    ["argentine", "Argentine", "Latin America and the Caribbean"],
  ].map(([slug, adjective, region]) => ({
    key: `enwiki-${slug}-fashion-designers`,
    label: `English Wikipedia ${adjective} fashion designers`,
    type: "wikipedia_category",
    url: `https://en.wikipedia.org/wiki/Category:${adjective.replaceAll(" ", "_")}_fashion_designers`,
    region,
    seasonOrDate: "continuing",
    enabled: true,
    language: "en",
    category: `Category:${adjective} fashion designers`,
  })),
  { key: "operator-wikipedia-mapping", label: "Reviewed operator Wikipedia mappings", type: "internal_registry", url: "operator://wikipedia-mapping", region: "global", seasonOrDate: "continuing", enabled: false, accessMode: "manual" },
  { key: "cfda-members", label: "Council of Fashion Designers of America members", type: "industry_directory", url: "https://cfda.com/members/", region: "North America", seasonOrDate: "continuing", enabled: false, accessMode: "manual" },
  { key: "fhcm-calendars", label: "FHCM official Paris calendars", type: "fashion_week", url: "https://www.fhcm.paris/en/upcoming-seasons-and-previous-editions", region: "Europe", seasonOrDate: "seasonal", enabled: false, accessMode: "manual" },
  { key: "cnmi-members", label: "Camera Nazionale della Moda Italiana members", type: "industry_directory", url: "https://www.cameramoda.it/en/associazione/members/", region: "Europe", seasonOrDate: "continuing", enabled: false, accessMode: "manual" },
  { key: "tokyo-fashion-week", label: "Japan Fashion Week Organization schedule and archive", type: "fashion_week", url: "https://rakutenfashionweektokyo.com/en/", region: "East Asia", seasonOrDate: "seasonal", enabled: false, accessMode: "manual" },
  { key: "shanghai-fashion-week", label: "Shanghai Fashion Week official schedule", type: "fashion_week", url: "https://www.shanghaifashionweek.com/page/shfw/schedule?language=en", region: "East Asia", seasonOrDate: "seasonal", enabled: false, accessMode: "manual" },
  { key: "lakme-fashion-week", label: "Lakmé Fashion Week × FDCI designers and schedules", type: "fashion_week", url: "https://www.lakmefashionweek.co.in/home/designers_landing", region: "South Asia", seasonOrDate: "seasonal", enabled: false, accessMode: "manual" },
  { key: "south-african-fashion-week", label: "South African Fashion Week schedule and designer community", type: "fashion_week", url: "https://www.safashionweek.co.za/", region: "Africa", seasonOrDate: "seasonal", enabled: false, accessMode: "manual" },
  { key: "lagos-fashion-week", label: "Lagos Fashion Week schedule", type: "fashion_week", url: "https://lagosfashionweek.ng/", region: "Africa", seasonOrDate: "seasonal", enabled: false, accessMode: "manual" },
  { key: "sao-paulo-fashion-week", label: "São Paulo Fashion Week shows and lineups", type: "fashion_week", url: "https://spfw.com.br/desfiles/", region: "Latin America and the Caribbean", seasonOrDate: "seasonal", enabled: false, accessMode: "manual" },
  { key: "fashion-week-official", label: "Official fashion-week calendars and archives", type: "fashion_week", url: "operator://official-fashion-week-registry", region: "global", seasonOrDate: "seasonal", enabled: false, accessMode: "manual" },
  { key: "boutique-directories", label: "Reviewed multi-brand boutique directories", type: "boutique_directory", url: "operator://boutique-source-registry", region: "global", seasonOrDate: "historical-and-current", enabled: false, accessMode: "manual" },
]);

export function discoverySource(key) {
  return WIKIPEDIA_DISCOVERY_SOURCES.find((source) => source.key === key) || null;
}
